# Generated by Django 2.0.3 on 2019-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='item',
            field=models.ManyToManyField(related_name='shoppingCarts', to='orders.Pizza'),
        ),
    ]
