# Generated by Django 2.0.3 on 2019-11-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppingamount',
            name='amount',
        ),
    ]
