# Generated by Django 2.0.3 on 2019-09-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
